[project]
name = "familyconnect-agents"
version = "1.0.0"
description = "FamilyConnect Agents for GenAI OS"
dependencies = [
    "genai-protocol>=1.0.9",
    "httpx>=0.25.0",
    "asyncio-mqtt>=0.13.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
