# Add this to your existing GenAI OS docker-compose.yml
version: '3.8'

services:
  # Add FamilyConnect to your existing GenAI OS setup
  familyconnect:
    build: .
    container_name: familyconnect-agents
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    networks:
      - genai-network
    depends_on:
      - genai-backend  # Replace with your GenAI OS backend service name
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/agents/message"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

networks:
  genai-network:
    external: true  # Use your existing GenAI OS network

# If you need to expose the FamilyConnect agents to other containers:
# The agents will be available at:
# - http://familyconnect:5000/api/agents/message (from within Docker network)
# - http://localhost:5000/api/agents/message (from host)
# - http://host.docker.internal:5000/api/agents/message (from GenAI OS containers)
